---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: hsl-realtime-demo-frontend
spec:
  selector:
    matchLabels:
      app: hsl-realtime-demo-frontend
  replicas: 1
  template:
    metadata:
      labels:
        app: hsl-realtime-demo-frontend
    spec:
      containers:
      - name: frontend
        image: eu.gcr.io/taneli-sandbox/hsl-realtime-demo-frontend:v9
        readinessProbe:
          httpGet:
            path: /healthz
            scheme: HTTP
            port: 8080
        env:
          - name: REDIS_HOST
            valueFrom:
              configMapKeyRef:
                name: hsl-realtime-frontend-config
                key: redisHost
          - name: REDIS_PORT
            valueFrom:
              configMapKeyRef:
                name: hsl-realtime-frontend-config
                key: redisPort
          - name: MAPS_APIKEY
            valueFrom:
              configMapKeyRef:
                name: hsl-realtime-frontend-config
                key: apiKey
          - name: FRONTEND_URL
            valueFrom:
              configMapKeyRef:
                name: hsl-realtime-frontend-config
                key: frontendUrl
        ports:
        - containerPort: 8080
---
kind: Service
apiVersion: v1
metadata:
  name: hsl-realtime-demo-frontend-service
spec:
  type: NodePort
  selector:
    app: hsl-realtime-demo-frontend
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: hsl-realtime-demo-frontend-ingress
spec:
  backend:
    serviceName: hsl-realtime-demo-frontend-service
    servicePort: 80
